#!/bin/bash
export ANDROID_JAVA_HOME=$JAVA_HOME
export PATH=${PATH}:~/android-sdk/tools
export PATH=${PATH}:~/android-sdk/platform-tools
export PATH=${PATH}:~/bin
export USE_CCACHE=1
export CCACHE_DIR=/mnt/b59ee394-ecc6-45b0-b5e6-244bb44528ae/ccache
export CCACHE_HASHDIR=$CCACHE_DIR
export OUT_DIR_COMMON_BASE=/mnt/b59ee394-ecc6-45b0-b5e6-244bb44528ae/NEW
. build/envsetup.sh
make installclean
time brunch presto

